server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/bidding_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds


google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/v1/auth/oauth2/callback}

logging:
  pattern:
    level: "%5p [${spring.application.name:app},traceId=%X{traceId}]"
