server:
  port: 8088
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: identity-service
            uri: http://localhost:8080
            predicates:
              - Path=${app.api-prefix}/identity/**
            filters:
              - StripPrefix=2
          - id: auction-service
            uri: http://localhost:8081
            predicates:
              - Path=${app.api-prefix}/auction/**
            filters:
              - StripPrefix=2
          - id: bidding-service
            uri: http://localhost:8082
            predicates:
              - Path=${app.api-prefix}/bidding/**
            filters:
              - StripPrefix=2
          - id: bidding-service-ws
            uri: ws://localhost:8082
            predicates:
              - Path=${app.api-prefix}/bidding-ws/**
            filters:
              - StripPrefix=2
          - id: notification-service
            uri: http://localhost:8083
            predicates:
              - Path=${app.api-prefix}/notification/**
            filters:
              - StripPrefix=2

security:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-please-32bytes}

logging:
  pattern:
    level: "%5p [${spring.application.name:app},traceId=%X{traceId}]"
